version: "2"
services:
  web:
    build: .
    command: api/bin/web
    environment:
      - AUTOSCALE=false
      - DEVELOPMENT=true
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - BUILD_CLUSTER
      - CLIENT_ID=dev@convox.com
      - CLOUDFORMATION_TOPIC
      - CLUSTER
      - CUSTOM_TOPIC
      - DEBUG=false
      - DOCKER_IMAGE_API=rack/web
      - DYNAMO_BUILDS
      - DYNAMO_RELEASES
      - ENCRYPTION_KEY
      - INTERNAL
      - NOTIFICATION_HOST
      - NOTIFICATION_TOPIC
      - PASSWORD
      - PRIVATE
      - PROVIDER
      - RACK
      - RELEASE
      - ROLLBAR_TOKEN=f67f25b8a9024d5690f997bd86bf14b0
      - SECURITY_GROUP
      - SEGMENT_WRITE_KEY=KLvwCXo6qcTmQHLpF69DEwGf9zh7lt9i
      - SETTINGS_BUCKET
      - STACK_ID
      - SUBNETS
      - SUBNETS_PRIVATE
      - VPC
      - VPCCIDR
      - LOG_GROUP
      - PROCESS=web
    ports:
      - 80:3000
      - 443:4443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  monitor:
    build: .
    command: api/bin/monitor
    environment:
      - DEVELOPMENT=true
      - AUTOSCALE=false
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - BUILD_CLUSTER
      - CLIENT_ID=dev@convox.com
      - CLOUDFORMATION_TOPIC
      - CLUSTER
      - CUSTOM_TOPIC
      - DEBUG=false
      - DOCKER_IMAGE_API=rack/web
      - DYNAMO_BUILDS
      - DYNAMO_RELEASES
      - ENCRYPTION_KEY
      - NOTIFICATION_HOST
      - NOTIFICATION_TOPIC
      - ON_DEMAND_MIN_COUNT
      - PASSWORD
      - PRIVATE
      - PROVIDER
      - RACK
      - RELEASE
      - ROLLBAR_TOKEN=f67f25b8a9024d5690f997bd86bf14b0
      - SECURITY_GROUP
      - SEGMENT_WRITE_KEY=KLvwCXo6qcTmQHLpF69DEwGf9zh7lt9i
      - SPOT_INSTANCES
      - STACK_ID
      - SUBNETS
      - SUBNETS_PRIVATE
      - VPC
      - LOG_GROUP
      - PROCESS=monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
