web:
  build: .
  environment:
    - DEVELOPMENT=true
    - AWS_REGION
    - AWS_ACCESS
    - AWS_SECRET
    - CLIENT_ID=dev@convox.com
    - CLUSTER
    - CUSTOM_TOPIC
    - DOCKER_IMAGE_BUILD
    - DYNAMO_BUILDS
    - DYNAMO_RELEASES
    - ENCRYPTION_KEY
    - MIXPANEL_TOKEN=43fb68427548c5e99978a598a9b14e55
    - PASSWORD
    - RACK
    - REGISTRY_HOST
    - RELEASE=latest
    - ROLLBAR_TOKEN=f67f25b8a9024d5690f997bd86bf14b0
    - SUBNETS
    - VPC
  ports:
    - 80:3000
    - 443:4443
  volumes:
    - ./:/go/src/github.com/convox/rack/api
    - /var/run/docker.sock:/var/run/docker.sock
registry:
  environment:
    - SETTINGS_FLAVOR=local
    - PASSWORD
  image: convox/registry
  ports:
    - 5000:443
